### PR TITLE
clojurize fixed

### PR DESCRIPTION
**Pull request by cldwalker**
Added another assertion just to be explicit about around clojurize edge case behavior. Also added travis since tests pass. Could you turn on travis for this repo?

### CODE REVIEW

**Comment by cldwalker** [comment]
Strange. I didn't expect the first commit to actually close #1 until it had been merged to master. @rsanheim or @spicycode does that seem like buggy behavior?

**Comment by qtrfeast** [comment]
Reviewed code and ran tests. Looks good @cldwalker.

**Comment by qtrfeast** [comment]
Also as I suspected, once this issue was closed #1 was closed and reflects being closed by 2081a692aa85180f249e7ed89ae2cd07df5780ac.

**Comment by alandipert** [comment]
Rad, thanks budes! I'll wire up Travis.

**Pull request merged**
